### ISSUE TITLE
where are splits.yaml and stain_normalisation_target.png?

### ISSUE THREAD

**Issue by jianxinhou** [msahasrabudhe/miccai2020_self_sup_nuclei_seg#1]
hello, when I use your code , it shows that it can't find splits.yaml and stain_normalisation_target.png. so can you tell me how can I get these files ,thank you!

**Comment by msahasrabudhe** [comment]
Hello, 

Thank you for pointing out this issue. I have added these files to the `data_processing` directory. They are to be placed in the directory to which `options.dataroot` points.

**Comment by jianxinhou** [comment]
Thank you! it works!
