### ISSUE TITLE
nepochs=10000?

### ISSUE THREAD

**Issue by jianxinhou** [msahasrabudhe/miccai2020_self_sup_nuclei_seg#2]
Hello again, I found that the "nepochs=10000" in your config, and I took 3 hours to train for 100 epochs.  I will cost 300 hours to finish it. So Can you tell me some more details about your training, such as how many nepochs you used and how long time finished it. Thank you!

**Comment by msahasrabudhe** [comment]
Hello,

You should be able to observe a plausible result soon (around 100-125 epochs). We observed that 300 epochs were good enough for a our models.

**Comment by jianxinhou** [comment]
Got it, Thank you!
