### ISSUE TITLE
where are program for AJI,AHD and ADC

### ISSUE THREAD

**Issue by HonyoLAN** [msahasrabudhe/miccai2020_self_sup_nuclei_seg#3]
Hello, I have got the predicted mask according to the project. 
But I wonder how you calculate the ADC, AJI and AHD. So can you tell me how can I get these evaluation script ,thank you!
Sincerely!

**Comment by msahasrabudhe** [comment]
Hello,

I have added the functions to compute these metrics. You can find them here: https://github.com/msahasrabudhe/miccai2020_self_sup_nuclei_seg/blob/master/metrics.py

**Comment by HonyoLAN** [comment]
Thank you!
