### ISSUE TITLE
dataroot

### ISSUE THREAD

**Issue by xiongxuechun** [msahasrabudhe/miccai2020_self_sup_nuclei_seg#4]
hello, when I use your code , it shows that it can't find slide_files. so can you tell me how can I get these files , how to use ourself dataset, and the make_tiles.py files. thank you!

**Comment by msahasrabudhe** [comment]
Hello, 

Please check [this link](https://github.com/msahasrabudhe/miccai2020_self_sup_nuclei_seg/tree/master/data_processing).

The whole slides I used for this project are too big to be added on Github, and as they are present in the TCGA database anyway, I did not share them via. any other means (Dropbox, OneDrive ...). I have therefore included a TCGA manifest file in the repository, which you can find at the above link. 
When you download the TCGA whole slides using manifest, it will create several sub-directories in the directory you download it into. You should then run make_tiles.py by appropriately setting the variables `root` (directory where you downloaded whole slides from TCGA), `SLIDE_SIZE` (variable determining the size of the individual tiles to be extracted, and `OUT_DIR` (location when you would like to save the extracted tiles. You would need to have [OpenSlide](https://openslide.org/) installed for this. 

Let me know if it helps.

**Comment by xiongxuechun** [comment]
I cannot from the link get tcga dataset. 
ERROR: Unable to download file https://api.gdc.cancer.gov/data/825963be-43a1-4666-b843-e59f158c688d
ERROR: 8ef18a40-91b2-426b-bdbc-5331356cdf14: 451 Client Error: UNAVAILABLE FOR LEGAL REASONS for url: https://api.gdc.cancer.gov/data/8ef18a40-91b2-426b-bdbc-5331356cdf14: {"message":"Request contains a redacted file(s): ['8ef18a40-91b2-426b-bdbc-5331356cdf14'], action not allowed"}

**Comment by msahasrabudhe** [comment]
Ah, yes, I forgot. Downloads from TCGA are suspended for the moment (see Nikolaus Schultz's comment [here](https://groups.google.com/g/cbioportal/c/m99XAnmF87w)). 
You will only be able to download them when it is resumed once again. 
Unfortunately, I cannot help in this case.

**Comment by xiongxuechun** [comment]
Thank you.
